austin_bikeshare_demo:
  outputs:
    dev:
      dataset: london_bicycles
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: EU
      method: oauth
      priority: interactive
      project: keen-philosophy-488314-a6
      threads: 1
      type: bigquery
  target: dev
my_first_dbt:
  outputs:
    dev:
      dataset: newer
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: EU
      method: oauth
      priority: interactive
      project: keen-philosophy-488314-a6
      threads: 1
      type: bigquery
  target: dev
