version: 1

models:
  - name: fact_trips
    description: "Fact table for bike trips."
    columns:
      - name: rental_id
        description: "The primary key for this fact_trips table"
        tests:
          - unique
          - not_null

      - name: bike_id
        description: "The foreign key to the dim_bike dimension table"
        tests:
          - not_null
          - relationships:
              # Uncomment the line 'arguments:' to resolve
              # MissingArgumentsPropertyInGenericTestDeprecation Warnings
              # Warnings appear dbt-core >= 1.10 environment
              # 'arguments:' will not work in older versions of dbt < 1.10
              arguments:
                to: ref('dim_bike')
                field: bike_id